default:
  image: 676826599814.dkr.ecr.ap-northeast-2.amazonaws.com/gitlab-runner-image-aws-sdk:1.0

variables:
  AWS_ROLE_SESSION_NAME: "gitlab-$CI_PIPELINE_ID-$CI_JOB_NAME"

include:
  - project: 'common/gitlab-script'
    ref: v2.5
    file: '/template/.before-script-template.yml'
  - project: 'common/gitlab-script'
    ref: v2.5
    file: '/template/.infra-workflow-script-template.yml'
  - project: 'common/gitlab-script'
    ref: v2.5
    file: '/template/.infra-job-template.yml'

stages:          # List of stages for jobs, and their order of execution
  - terraform-plan
  - terraform-apply
  - terraform-plan-prd
  - terraform-apply-prd

new-terraform-plan: 
  stage: terraform-plan
  extends: .infra-terraform-plan-template
  resource_group: ${target}-${ENV}
  cache:
    key: ${CI_COMMIT_BRANCH}-${target}-terraform
    paths:
      - terraform/${target}/.terraform
  variables:
    target: "new_app"

new-terraform-apply: 
  stage: terraform-apply
  extends: .infra-terraform-apply-template
  resource_group: ${target}-${ENV}
  cache:
    key: ${CI_COMMIT_BRANCH}-${target}-terraform
    paths:
      - terraform/${target}/.terraform
  when: manual
  variables:
    target: "new_app"

new-terraform-plan-prd: 
  stage: terraform-plan-prd
  extends: .infra-terraform-plan-template
  resource_group: ${target}-${ENV}
  cache:
    key: ${CI_COMMIT_BRANCH}-${target}-terraform
    paths:
      - terraform/${target}/.terraform
  variables:
    target: "new_app"
    ENV: prd
  rules:
  - if: $CI_COMMIT_BRANCH == "master" 
    changes:
      - terraform/${target}/**

new-terraform-apply-prd: 
  stage: terraform-apply-prd
  extends: .infra-terraform-apply-template
  resource_group: ${target}-${ENV}
  cache:
    key: ${CI_COMMIT_BRANCH}-${target}-terraform
    paths:
      - terraform/${target}/.terraform
  when: manual
  variables:
    target: "new_app"
    ENV: prd
  needs:
    - new-terraform-plan-prd
  rules:
  - if: $CI_COMMIT_BRANCH == "master" 
    changes:
      - terraform/${target}/**

new-terraform-database-plan: 
  stage: terraform-plan
  extends: .infra-terraform-plan-template
  resource_group: ${target}-${ENV}
  cache:
    key: ${CI_COMMIT_BRANCH}-${target}-terraform
    paths:
      - terraform/${target}/.terraform
  variables:
    target: "database"

new-terraform-database-apply: 
  stage: terraform-apply
  extends: .infra-terraform-apply-template
  resource_group: ${target}-${ENV}
  cache:
    key: ${CI_COMMIT_BRANCH}-${target}-terraform
    paths:
      - terraform/${target}/.terraform
  when: manual
  variables:
    target: "database"

new-terraform-database-plan-prd: 
  stage: terraform-plan-prd
  extends: .infra-terraform-plan-template
  resource_group: ${target}-${ENV}
  cache:
    key: ${CI_COMMIT_BRANCH}-${target}-terraform
    paths:
      - terraform/${target}/.terraform
  variables:
    target: "database"
    ENV: prd
  rules:
  - if: $CI_COMMIT_BRANCH == "master" 
    changes:
      - terraform/${target}/**

new-terraform-database-apply-prd: 
  stage: terraform-apply-prd
  extends: .infra-terraform-apply-template
  resource_group: ${target}-${ENV}
  cache:
    key: ${CI_COMMIT_BRANCH}-${target}-terraform
    paths:
      - terraform/${target}/.terraform
  when: manual
  variables:
    target: "database"
    ENV: prd
  needs:
    - new-terraform-database-plan-prd
  rules:
  - if: $CI_COMMIT_BRANCH == "master" 
    changes:
      - terraform/${target}/**

