default:
  image: 676826599814.dkr.ecr.ap-northeast-2.amazonaws.com/gitlab-runner-image-aws-sdk:1.0

variables:
  AWS_ROLE_SESSION_NAME: "gitlab-$CI_PIPELINE_ID-$CI_JOB_NAME"

include:
  - project: "common/gitlab-script"
    ref: v2.5
    file: "/template/.before-script-template.yml"
  - project: "common/gitlab-script"
    ref: v2.5
    file: "/template/.infra-workflow-script-template.yml"
  - project: "common/gitlab-script"
    ref: v2.5
    file: "/template/.infra-job-template.yml"

stages:
  - terraform-plan
  - terraform-apply
  - terraform-plan-prd
  - terraform-apply-prd

terraform-plan:
  stage: terraform-plan
  extends: .infra-terraform-plan-template
  resource_group: ${ENV}
  cache:
    key: ${CI_COMMIT_BRANCH}-terraform
    paths:
      - terraform/.terraform
  rules:
    - if: $IS_FEATURE == "true"

terraform-apply:
  stage: terraform-apply
  extends: .infra-terraform-apply-template
  resource_group: ${ENV}
  cache:
    key: ${CI_COMMIT_BRANCH}-terraform
    paths:
      - terraform/.terraform
  rules:
    - if: $IS_FEATURE == "false"

terraform-plan-prd:
  stage: terraform-plan-prd
  extends: .infra-terraform-plan-template
  resource_group: prd
  variables:
    ENV: prd
  cache:
    key: ${CI_COMMIT_BRANCH}-terraform
    paths:
      - terraform/.terraform
  only:
    - master

terraform-apply-prd:
  stage: terraform-apply-prd
  extends: .infra-terraform-apply-template
  resource_group: prd
  variables:
    ENV: prd
  when: manual
  needs:
    - terraform-plan-prd
  cache:
    key: ${CI_COMMIT_BRANCH}-terraform
    paths:
      - terraform/.terraform
  only:
    - master

### new prod environment ###

terraform-plan-nprd:
  stage: terraform-plan-prd
  extends: .infra-terraform-plan-template
  resource_group: prd
  variables:
    ENV: nprd
  cache:
    key: ${CI_COMMIT_BRANCH}-terraform
    paths:
      - terraform/.terraform
  only:
    - master

terraform-apply-nprd:
  stage: terraform-apply-prd
  extends: .infra-terraform-apply-template
  resource_group: prd
  variables:
    ENV: nprd
  when: manual
  needs:
    - terraform-plan-nprd
  cache:
    key: ${CI_COMMIT_BRANCH}-terraform
    paths:
      - terraform/.terraform
  only:
    - master
