#!/bin/bash

if [ "$0" = "$BASH_SOURCE" ]
then
    echo "$0: Please source this file."
    echo "e.g. source ./setenv configurations/data-rnd-us-vet1-v1"
    return 1
fi

if [ -z "$1" ]
then
    echo "setenv: You must provide the name of the configuration file."
    echo "e.g. source ./setenv configurations/data-rnd-us-vet1-v1"
    return 1
fi

# Get directory we are running from
DIR=$(pwd)
DATAFILE="$DIR/$1"

if [ ! -d "$DIR/configurations" ]; then
    echo "setenv: Must be run from the root directory of the terraform project."
    return 1
fi

if [ ! -f "$DATAFILE" ]; then
    echo "setenv: Configuration file not found: $DATAFILE"
    return 1
fi

# Get env from DATAFILE
REGION=$(grep aws_shot_region "$DATAFILE" | awk -F '=' '{print $2}' | sed -e 's/["\ ]//g')
ENVIRONMENT=$(grep s3_tfstate_dir "$DATAFILE" | awk -F '=' '{print $2}' | sed -e 's/["\ ]//g')
S3BUCKETREGION=$(grep ^region "$DATAFILE" | awk -F '=' '{print $2}' | sed -e 's/["\ ]//g')
S3TFSTATEFILE=$(grep s3_tfstate_file "$DATAFILE" | awk -F '=' '{print $2}' | sed -e 's/["\ ]//g')

if [ -z "$S3BUCKETREGION" ]
then
    echo "setenv: 's3_bucket_region' variable not set in configuration file."
    return 1
fi
# if [ -z "$S3TFSTATEFILE" ]
# then
#     echo "setenv: 's3_tfstate_file' variable not set in configuration file."
#     echo "e.g. s3_tfstate_file=\"infrastructure.tfstate\""
#     return 1
# fi

cat << EOF > "$DIR/backend.tf"
terraform {
  backend "s3" {
    bucket = "s3-${REGION}-${ENVIRONMENT}-new-apps-manage-tfstate"
    key    = "${ENVIRONMENT}/${S3TFSTATEFILE}"
    region = "${S3BUCKETREGION}"
    dynamodb_table = "dynamo-${REGION}-${ENVIRONMENT}-new-app-terraform-lock"
    encrypt       = true
  }
}
EOF

# Verify if user has valid AWS credentials in current session
#if CALLER_IDENTITY=$(aws sts get-caller-identity 2>&1); then
#    echo "Using AWS Identity: ${CALLER_IDENTITY}"
#else
#    echo "setenv: Please run 'get-temporary-aws-credentials.sh' first"
#    return 1
#fi

export DATAFILE
export TF_WARN_OUTPUT_ERRORS=1
rm -rf "$DIR/.terraform"

echo "$DIR"
cat backend.tf
cd "$DIR"

echo "setenv: Initializing terraform"
terraform init > /dev/null

