FROM alpine:3.15.2

RUN apk update && apk add yq git curl --no-cache
RUN curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
RUN chmod +x /usr/local/bin/argocd
