default:
  image: 676826599814.dkr.ecr.ap-northeast-2.amazonaws.com/gitlab-runner-image-aws-sdk:1.0

variables:
  AWS_ROLE_SESSION_NAME: "gitlab-$CI_PIPELINE_ID-$CI_JOB_NAME"
  SYSTEM_NAME: "argoapps"
  ARGO_CD_URL: "argo.mgmt.stg.naemo.io:80"

cache:
  key: $CI_COMMIT_BRANCH-terraform
  paths:
    - terraform/.terraform

include:
  - project: 'common/gitlab-script'
    ref: v3.4
    file: '/template/.before-script-template.yml'
  - project: 'common/gitlab-script'
    ref: v3.4
    file: '/template/.infra-workflow-script-template.yml'

stages:
  - stg_ec2_batch
  - stg_rds
  - stg_eks
  - stg_argo

ec2_stop:
  stage: stg_ec2_batch
  tags: 
    - shared
  environment:
    name: stg
  extends: .aws-assume-template
  script:
    - python3 ec2-batch-stop.py
  when: manual
  resource_group: stg

ec2_start:
  stage: stg_ec2_batch
  tags: 
    - shared
  environment:
    name: stg
  extends: .aws-assume-template
  script:
    - python3 ec2-batch-start.py
  when: manual
  resource_group: stg

rds_stop:
  stage: stg_rds
  tags: 
    - shared
  environment:
    name: stg
  extends: .aws-assume-template
  script:
    - python3 db-stop.py
  when: manual
  resource_group: stg

rds_start:
  stage: stg_rds
  tags: 
    - shared
  environment:
    name: stg
  extends: .aws-assume-template
  script:
    - python3 db-start.py
  when: manual
  resource_group: stg

eks_stop:
  stage: stg_eks
  tags: 
    - shared
  environment:
    name: stg
  extends: .aws-assume-template
  script:
    - python3 eks-stop.py
  when: manual
  resource_group: stg

argo_app_create:
  stage: stg_argo
  tags:
    - shared 
  environment:
    name: stg    
  image: 676826599814.dkr.ecr.ap-northeast-2.amazonaws.com/gitlab-runner-image-argocli:1.0      
  script:
    - export no=$(argocd app list --auth-token ${ARGO_TOKEN} --server ${ARGO_CD_URL} --grpc-web --plaintext | grep "^${SYSTEM_NAME} " | wc -l)
    - >-
      if [ $no -eq 0 ]; then
        argocd app create ${SYSTEM_NAME} \
        --auth-token ${ARGO_TOKEN} \
        --server ${ARGO_CD_URL} \
        --repo http://gitlab.mgmt.an2.shd.naemo.io/naemo/infra-appofapps.git \
        --path ./stg \
        --dest-name ${EKS_CLUSTER} \
        --dest-namespace ${SYSTEM_NAME} \
        --project apps \
        --sync-option CreateNamespace=true \
        --grpc-web \
        --plaintext 

        argocd app sync $SYSTEM_NAME --force --auth-token $ARGO_TOKEN --server $ARGO_CD_URL --plaintext --grpc-web
        argocd app wait $SYSTEM_NAME --timeout 600 --auth-token $ARGO_TOKEN --server $ARGO_CD_URL --plaintext --health --grpc-web
      fi
  when: manual
  resource_group: stg   

argo_app_delete:
  stage: stg_argo
  tags:
    - shared 
  environment:
    name: stg    
  image: 676826599814.dkr.ecr.ap-northeast-2.amazonaws.com/gitlab-runner-image-argocli:1.0 
  script:
    - export no=$(argocd app list --auth-token ${ARGO_TOKEN} --server ${ARGO_CD_URL} --grpc-web --plaintext | grep "^${SYSTEM_NAME} " | wc -l)
    - >-    
      if [ $no -gt 0 ]; then
        argocd app delete ${SYSTEM_NAME} \
        --auth-token ${ARGO_TOKEN} \
        --server ${ARGO_CD_URL} \
        --grpc-web \
        --plaintext
      fi      
  when: manual
  resource_group: stg 



