workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^feature.*/ || $CI_COMMIT_REF_NAME =~ /^bugfix.*/
      variables:
        ENV: "dev"
        IS_FEATURE: "true"
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event"
      variables:
        ENV: "dev-test"
        IS_FEATURE: "false"       
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        ENV: "stg"
        IS_FEATURE: "true"     
    - if: $CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE != "merge_request_event"
      variables:
        ENV: "stg"
        IS_FEATURE: "false"
