apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "web-service.fullname" . }}-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "web-service.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "web-service.fullname" . }}-secret
    creationPolicy: Owner
  data:
  {{- toYaml .Values.envVariablesFromSecrets | nindent 4}}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "web-service.fullname" . }}-pms
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "web-service.fullname" . }}-pms
    kind: SecretStore
  target:
    name: {{ include "web-service.fullname" . }}-pms
    creationPolicy: Owner
  data:
  {{- toYaml .Values.envVariablesFromParams | nindent 4}}

