apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ include "web-service.fullname" . }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "web-service.serviceAccountName" . }}-secret
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ include "web-service.fullname" . }}-pms
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "web-service.serviceAccountName" . }}-secret

