{{- if .Values.serviceAccountSecret.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "web-service.serviceAccountName" . }}-secret
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
