apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:eks:ap-northeast-2:676826599814:fargateprofile/eks-an2-shd-gitlab/coredns/a8bf70d7-5707-a27f-f6d0-97ee1a685fae
      username: system:node:{{SessionName}}
      groups:
        - system:bootstrappers
        - system:nodes
        - system:node-proxier
    - rolearn: arn:aws:eks:ap-northeast-2:676826599814:fargateprofile/eks-an2-shd-gitlab/gitlab-runner/0abf70d5-e61f-3d8f-a4b0-9464c27389de
      username: system:node:{{SessionName}}
      groups:
        - system:bootstrappers
        - system:nodes
        - system:node-proxier
    - rolearn: arn:aws:iam::676826599814:role/shd-gitlab-role
      username: gitlab-instance
      groups:
        - system:masters
    - rolearn: arn:aws:iam::676826599814:role/shd-bastion-role
      username: bastion-instance
      groups:
        - system:masters
    - rolearn: arn:aws:iam::676826599814:role/coredns-20220210031352520900000002
      username: system:node:{{SessionName}}
      groups:
        - system:bootstrappers
        - system:nodes
        - system:node-proxier
    - rolearn: arn:aws:iam::676826599814:role/gitlab-runner-20220210025907410000000002
      username: system:node:{{SessionName}}
      groups:
        - system:bootstrappers
        - system:nodes
        - system:node-proxier
  mapUsers: |
    - userarn: arn:aws:iam::676826599814:user/Ian
      username: ian
      groups:
        - system:masters
    - userarn: arn:aws:iam::676826599814:user/kmz765@lgcns.com
      username: kmz765@lgcns.com
      groups:
        - system:masters