default:
  image: 676826599814.dkr.ecr.ap-northeast-2.amazonaws.com/gitlab-runner-image-aws-sdk:1.0

variables:
  AWS_ROLE_SESSION_NAME: "gitlab-$CI_PIPELINE_ID-$CI_JOB_NAME"

cache:
  key: $CI_COMMIT_BRANCH-terraform
  paths:
    - .terraform

include:
  - project: 'common/gitlab-script'
    ref: v2.5
    file: '/template/.before-script-template.yml'
  - project: 'common/gitlab-script'
    ref: v2.5
    file: '/template/.infra-workflow-script-template.yml'
  - project: 'common/gitlab-script'
    #ref: v2.5
    file: '/template/.slack-noti-script.yml'

stages:          # List of stages for jobs, and their order of execution
  - terraform-plan
  - terraform-apply

after_script:
  - !reference [.slack-noti, after_script]

terrafom-plan:       # This job runs in the build stage, which runs first.
  stage: terraform-plan
  tags: 
    - shared
  environment:
    name: $ENV
  script:
    - cd terraform
    - terraform init
    - terraform plan -var-file configurations/iam.tfvars
  only:
    variables:
      - $IS_FEATURE == "true"
  resource_group: $ENV

terrafom-apply:       # This job runs in the build stage, which runs first.
  stage: terraform-apply
  tags: 
    - shared
  environment:
    name: $ENV
  script:
    - aws sts get-caller-identity
    - cd terraform
    - terraform init
    - terraform apply -auto-approve -var-file configurations/iam.tfvars
  only:
    variables:
      - $IS_FEATURE == "false"
  resource_group: $ENV
