default:
  image: 676826599814.dkr.ecr.us-east-2.amazonaws.com/gitlab-runner-image-aws-sdk:1.0

variables:
  AWS_ROLE_SESSION_NAME: "gitlab-$CI_PIPELINE_ID-$CI_JOB_NAME"

cache:
  key: $CI_COMMIT_BRANCH-terraform
  paths:
    - .terraform

include:
  - project: 'common/gitlab-script'
    file: '/template/.before-script-template.yml'
  - project: 'common/gitlab-script'
    file: '/template/.workflow-script-template.yml'

stages:          # List of stages for jobs, and their order of execution
  - terraform-plan
  - terraform-apply

terrafom-plan:       # This job runs in the build stage, which runs first.
  stage: terraform-plan
  tags: 
    - shared
  environment:
    name: $ENV
  extends: .aws-assume-template
  script:
    - cd terraform/$ENV
    - terraform init
    - terraform plan -var-file configurations/application-$ENV.tfvars
  only:
    variables:
      - $IS_FEATURE == "true"
  resource_group: $ENV

terrafom-apply:       # This job runs in the build stage, which runs first.
  stage: terraform-apply
  tags: 
    - shared
  environment:
    name: $ENV
  extends: .aws-assume-template
  script:
    - cd terraform/$ENV
    - terraform init
    - terraform apply -auto-approve -var-file configurations/application-$ENV.tfvars
  only:
    variables:
      - $IS_FEATURE == "false"
  resource_group: $ENV
